services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    volumes:
      - ./models:/app/models
      - ./policies:/app/policies
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_EMBED_MODEL=nomic-embed-text
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - api
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_ALLOW_HOSTS=*